//Generated by Gemini

#ifndef ASSERT_H
#define ASSERT_H

#include <cstdlib>
#include <iostream>
#include <cstdio>  // Required for snprintf
#include <cstdarg> // Required for va_list, va_start, va_end

// --- Internal Helper Function ---
// This function performs the actual printing.
// It explicitly takes a format string, which can be nullptr if no message.
inline void deq_assert_fail_print_impl(const char* cond_str, const char* file, int line, const char* fmt_str, ...) {
    std::cerr << "Assertion failed: (" << cond_str << "), file " << file
              << ", line " << line;

    // Only print the formatted message if fmt_str is not nullptr AND not an empty string.
    if (fmt_str != nullptr && fmt_str[0] != '\0') {
        std::cerr << ": ";

        char buffer[1024]; // Adjust buffer size as needed. Consider dynamic allocation for very long messages.
        va_list args;
        va_start(args, fmt_str);
        // vsnprintf writes up to n-1 characters plus null terminator.
        // It returns the number of characters that would have been written,
        // excluding the null terminator, if the buffer was large enough.
        std::vsnprintf(buffer, sizeof(buffer), fmt_str, args);
        va_end(args);

        std::cerr << buffer;
    }
    std::cerr << std::endl;
    std::abort(); // Always abort on assertion failure
}

// --- Public Assertion Macros ---
#ifndef NDEBUG

// 1. Assertion without an extra message (original behavior)
#define deq_assert(cond) \
    do { \
        if (!(cond)) { \
            deq_assert_fail_print_impl(#cond, __FILE__, __LINE__, nullptr); \
        } \
    } while (0)

// 2. Assertion with an optional formatted message
//    Requires the user to explicitly call this version when they want a message.
//    Using a distinct name helps clarity.
#define deq_assert_msg(cond, fmt_str, ...) \
    do { \
        if (!(cond)) { \
            deq_assert_fail_print_impl(#cond, __FILE__, __LINE__, fmt_str, ##__VA_ARGS__); \
        } \
    } while (0)

#else // NDEBUG - Release mode

// In release mode, macros do nothing.
#define deq_assert(cond) ((void)0)
#define deq_assert_msg(cond, fmt_str, ...) ((void)0)

#endif // NDEBUG

#endif // ASSERT_H